FROM docker.io/intel/hpckit

# add crunch_user
RUN useradd -ms /bin/bash crunch_user

# Switch to crunch_user
USER crunch_user

# Change the Working Directory
WORKDIR /home/crunch_user

# PETSc install
RUN git clone https://gitlab.com/petsc/petsc.git petsc
WORKDIR /home/crunch_user/petsc
RUN git checkout v3.20.4
ARG PETSC_DIR=/home/crunch_user/petsc
ARG PETSC_ARCH=intel-opt
RUN ./configure --with-cc=icx --with-cxx=icpx --with-fc=ifx --with-debugging=0 --with-shared-libraries=0 --with-blas-lapack-dir=/opt/intel/oneapi/mkl/2024.0/lib --with-x=0 LIBS=-lstdc++ --with-c2html=0 --with-cxx-dialect=C++11 --with-mpi=0
RUN make $PETSC_DIR $PETSC_ARCH all
RUN make $PETSC_DIR $PETSC_ARCH check

WORKDIR /home/crunch_user

# CrunchTope install
RUN git clone https://github.com/CISteefel/CrunchTope.git crunchtope
WORKDIR /home/crunch_user/crunchtope/Source
RUN make

WORKDIR /home/crunch_user
