name: CrunchTope CI

on: [workflow_dispatch, push, pull_request]

env:
  # Customizing build type
  BUILD_TYPE: DEBUG

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: package-install
      run: |
        sudo apt-get -qq update
        sudo apt -qq install gfortran libopenmpi-dev libhdf5-openmpi-dev hdf5-helpers

    - name: directories-variables
      run: |
        echo "PETSC_DIR=$HOME/petsc" >> $GITHUB_ENV
        echo "PETSC_ARCH=debug" >> $GITHUB_ENV

    - name: petsc-install
      run: |
        git clone https://gitlab.com/petsc/petsc.git --branch v3.21.6 $PETSC_DIR
        cd $PETSC_DIR
        echo "CrunchTope >> Configuring petsc"
        PETSC_ARCH=$PETSC_ARCH ./configure --with-mpi=0 --with-debugging=1 --with-shared-libraries=1 --download-fblaslapack=1
        echo "CrunchTope >> Building petsc"
        make

    - uses: actions/checkout@v4
    
    - name: crunchtope-build
      run: |
        cd Source
        echo "Building CrunchTope"
        make
        
    - name: crunchtope-run1
      run: |
        cd Exercises/Ex1Speciation
        echo "Running Ex1Speciation"
        ../../Source/CrunchTope ShortCourse1.in
        
    - name: crunchtope-run2
      run: |
        cd Exercises/Ex2Advection
        echo "Running Ex2Advection"
        ../../Source/CrunchTope ShortCourse2.in
        
    - name: crunchtope-run3
      run: |
        cd Exercises/Ex3FickianDiffusion
        echo "Running Ex3FickianDiffusion"
        ../../Source/CrunchTope ShortCourse3.in
        
    - name: crunchtope-run4
      run: |
        cd Exercises/Ex4MulticomponentDiffusion
        echo "Running Ex4MulticomponentDiffusion"
        ../../Source/CrunchTope ShortCourse4.in
        
    - name: crunchtope-run5
      run: |
        cd Exercises/Ex5RolleTransverseDiffusion
        echo "Running Ex5RolleTransverseDiffusion"
        ../../Source/CrunchTope Rolle2D.in
        
    - name: crunchtope-run13
      run: |
        cd Exercises/Ex13UnsaturatedFlow
        echo "Running Ex13UnsaturatedFlow"
        ../../Source/CrunchTope ShortCourse13.in
        
    - name: crunchtope-run14
      run: |
        cd Exercises/Ex14UnsaturatedFlow_evaporation
        echo "Running Ex14UnsaturatedFlow_evaporation"
        ../../Source/CrunchTope ShortCourse14.in
        
     - name: crunchtope-run15
      run: |
        cd Exercises/Ex15UnsaturatedFlow_transient
        echo "Running Ex15UnsaturatedFlow_transient"
        ../../Source/CrunchTope ShortCourse15.in
        
     - name: crunchtope-run16
      run: |
        cd Exercises/Ex16UnsaturatedFlow2D
        echo "Running Ex16UnsaturatedFlow2D"
        ../../Source/CrunchTope ShortCourse16.in
